#!/bin/bash

# This script cleans up log, cache, and temporary data files generated by the project.
# It will permanently delete the contents of the specified directories and files.

# Get the directory where the script is located to ensure paths are correct
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "This script will permanently delete the following files and directories:"
echo ""
echo "Directories to be removed:"
echo "  - ${SCRIPT_DIR}/cache"
echo "  - ${SCRIPT_DIR}/web/cache"
echo "  - ${SCRIPT_DIR}/logs"
echo "  - ${SCRIPT_DIR}/results"
echo "  - ${SCRIPT_DIR}/web/logs"
echo "  - ${SCRIPT_DIR}/data/finnhub_data"
echo "  - ${SCRIPT_DIR}/data/sessions"
echo "  - ${SCRIPT_DIR}/tradingagents/dataflows/data_cache"
echo "  - ${SCRIPT_DIR}/web/data/finnhub_data"
echo "  - ${SCRIPT_DIR}/web/data/sessions"
echo "  - ${SCRIPT_DIR}/web/eval_results"
echo "  - ${SCRIPT_DIR}/eval_results"
echo ""
echo "Files to be removed:"
echo "  - ${SCRIPT_DIR}/data/progress_analysis_*.json"
echo "  - ${SCRIPT_DIR}/web/data/progress_analysis_*.json"
echo "  - ${SCRIPT_DIR}/daily_prices.log"
echo ""

# Ask for user confirmation
read -p "Are you sure you want to continue? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Cleaning cancelled."
    exit 1
fi

echo "Cleaning project files..."

# Use rm -rf for directories and rm -f for files. The -f flag suppresses errors if a file/dir doesn't exist.

# Remove cache directories
rm -rf "${SCRIPT_DIR}/cache"
rm -rf "${SCRIPT_DIR}/web/cache"

# Remove log directories
rm -rf "${SCRIPT_DIR}/logs"
rm -rf "${SCRIPT_DIR}/results"
rm -rf "${SCRIPT_DIR}/web/logs"

# Remove data directories and specific files
rm -rf "${SCRIPT_DIR}/data/finnhub_data"
rm -rf "${SCRIPT_DIR}/data/sessions"
rm -rf "${SCRIPT_DIR}/tradingagents/dataflows/data_cache"
rm -f "${SCRIPT_DIR}/data/progress_analysis_"*.json
rm -f "${SCRIPT_DIR}/web/data/progress_analysis_"*.json
rm -f "${SCRIPT_DIR}/daily_prices.log"

# Remove web data directories
rm -rf "${SCRIPT_DIR}/web/data/finnhub_data"
rm -rf "${SCRIPT_DIR}/web/data/sessions"

# Remove evaluation results
rm -rf "${SCRIPT_DIR}/web/eval_results"
rm -rf "${SCRIPT_DIR}/eval_results"

echo "Cleaning complete."
