@echo off

for /d /r . %%d in (__pycache__) do @if exist "%%d" rd /s /q "%%d"

REM This script cleans up log, cache, and temporary data files generated by the project.
REM It will permanently delete the contents of the specified directories and files.

ECHO Cleaning project files...

REM Remove cache directories
rmdir /s /q "%~dp0cache"
rmdir /s /q "%~dp0web\cache"

REM Remove log directories
rmdir /s /q "%~dp0logs"
rmdir /s /q "%~dp0results"
rmdir /s /q "%~dp0web\logs"
rmdir /s /q "%~dp0Strategy\__pycache__"

REM Remove data directories and specific files
rmdir /s /q "%~dp0data\finnhub_data"
rmdir /s /q "%~dp0data\sessions"
rmdir /s /q "%~dp0tradingagents\dataflows\data_cache"
del /q "%~dp0data\progress_analysis_*.json"
del /q "%~dp0web\data\progress_analysis_*.json"
del /q "%~dp0daily_prices.log"

REM Remove web data directories
rmdir /s /q "%~dp0web\data\finnhub_data"
rmdir /s /q "%~dp0web\data\sessions"

REM Remove evaluation results
rmdir /s /q "%~dp0web\eval_results"

REM Remove evaluation results
rmdir /s /q "%~dp0eval_results"

ECHO Cleaning complete.

PAUSE