version: '3.8'

services:
  trading-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./analysis reports:/app/analysis reports
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
